%% Generated by the Erlang ASN.1 compiler version:1.4.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module SPNEGOASNOneSpec



-record('NegTokenInit',{
mechTypes = asn1_NOVALUE, reqFlags = asn1_NOVALUE, mechToken = asn1_NOVALUE, mechListMIC = asn1_NOVALUE}).

-record('NegTokenResp',{
negState = asn1_NOVALUE, supportedMech = asn1_NOVALUE, responseToken = asn1_NOVALUE, mechListMIC = asn1_NOVALUE}).

